runtime: go112
default_expiration: "6h"
instance_class: B2
basic_scaling:
  max_instances: 4
  idle_timeout: 10m

handlers:
- url: /scripts
  static_dir: scripts
  secure: always
  redirect_http_response_code: 301
- url: /.*
  script: auto
  secure: always